TARGET := iphone:clang:18.6:13.0
ARCHS = arm64

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = KhmerTopButton

KhmerTopButton_FILES = Tweak.xm
KhmerTopButton_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
